version: '3.4'

services:
  crawler.api:
    image: ${DOCKER_REGISTRY-}crawlerapi
    build:
      context: .
      dockerfile: Crawler.API/Dockerfile
    networks:
      #- my_custom_network
      - internal
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      #- my_custom_network
      - internal

networks:
  internal: 
    driver: bridge

  #my_custom_network:
  #  external: true
